/* eslint-disable */
// @generated by protobuf-ts 2.11.1 with parameter ts_nocheck,eslint_disable,long_type_string
// @generated from protobuf file "student/student.proto" (package "student", syntax proto3)
// tslint:disable
// @ts-nocheck
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message student.StudentInfo
 */
export interface StudentInfo {
    /**
     * @generated from protobuf field: int64 id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: string name = 2
     */
    name: string;
    /**
     * @generated from protobuf field: int32 age = 3
     */
    age: number;
    /**
     * @generated from protobuf field: string class_name = 4
     */
    className: string;
}
/**
 * @generated from protobuf message student.CreateStudentRequest
 */
export interface CreateStudentRequest {
    /**
     * @generated from protobuf field: string name = 1
     */
    name: string;
    /**
     * @generated from protobuf field: int32 age = 2
     */
    age: number;
    /**
     * @generated from protobuf field: string class_name = 3
     */
    className: string;
}
/**
 * @generated from protobuf message student.CreateStudentReply
 */
export interface CreateStudentReply {
    /**
     * @generated from protobuf field: student.StudentInfo student = 1
     */
    student?: StudentInfo;
}
/**
 * @generated from protobuf message student.UpdateStudentRequest
 */
export interface UpdateStudentRequest {
    /**
     * @generated from protobuf field: int64 id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: string name = 2
     */
    name: string;
    /**
     * @generated from protobuf field: int32 age = 3
     */
    age: number;
    /**
     * @generated from protobuf field: string class_name = 4
     */
    className: string;
}
/**
 * @generated from protobuf message student.UpdateStudentReply
 */
export interface UpdateStudentReply {
    /**
     * @generated from protobuf field: student.StudentInfo student = 1
     */
    student?: StudentInfo;
}
/**
 * @generated from protobuf message student.DeleteStudentRequest
 */
export interface DeleteStudentRequest {
    /**
     * @generated from protobuf field: int64 id = 1
     */
    id: string;
}
/**
 * @generated from protobuf message student.DeleteStudentReply
 */
export interface DeleteStudentReply {
    /**
     * @generated from protobuf field: bool success = 1
     */
    success: boolean;
}
/**
 * @generated from protobuf message student.GetStudentRequest
 */
export interface GetStudentRequest {
    /**
     * @generated from protobuf field: int64 id = 1
     */
    id: string;
}
/**
 * @generated from protobuf message student.GetStudentReply
 */
export interface GetStudentReply {
    /**
     * @generated from protobuf field: student.StudentInfo student = 1
     */
    student?: StudentInfo;
}
/**
 * @generated from protobuf message student.ListStudentsRequest
 */
export interface ListStudentsRequest {
    /**
     * @generated from protobuf field: int32 page = 1
     */
    page: number;
    /**
     * @generated from protobuf field: int32 page_size = 2
     */
    pageSize: number;
}
/**
 * @generated from protobuf message student.ListStudentsReply
 */
export interface ListStudentsReply {
    /**
     * @generated from protobuf field: repeated student.StudentInfo students = 1
     */
    students: StudentInfo[];
    /**
     * @generated from protobuf field: int32 count = 2
     */
    count: number;
}
// @generated message type with reflection information, may provide speed optimized methods
class StudentInfo$Type extends MessageType<StudentInfo> {
    constructor() {
        super("student.StudentInfo", [
            { no: 1, name: "id", kind: "scalar", T: 3 /*ScalarType.INT64*/ },
            { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "age", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "class_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<StudentInfo>): StudentInfo {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "0";
        message.name = "";
        message.age = 0;
        message.className = "";
        if (value !== undefined)
            reflectionMergePartial<StudentInfo>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: StudentInfo): StudentInfo {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 id */ 1:
                    message.id = reader.int64().toString();
                    break;
                case /* string name */ 2:
                    message.name = reader.string();
                    break;
                case /* int32 age */ 3:
                    message.age = reader.int32();
                    break;
                case /* string class_name */ 4:
                    message.className = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: StudentInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 id = 1; */
        if (message.id !== "0")
            writer.tag(1, WireType.Varint).int64(message.id);
        /* string name = 2; */
        if (message.name !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.name);
        /* int32 age = 3; */
        if (message.age !== 0)
            writer.tag(3, WireType.Varint).int32(message.age);
        /* string class_name = 4; */
        if (message.className !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.className);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message student.StudentInfo
 */
export const StudentInfo = new StudentInfo$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CreateStudentRequest$Type extends MessageType<CreateStudentRequest> {
    constructor() {
        super("student.CreateStudentRequest", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "age", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "class_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<CreateStudentRequest>): CreateStudentRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.name = "";
        message.age = 0;
        message.className = "";
        if (value !== undefined)
            reflectionMergePartial<CreateStudentRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CreateStudentRequest): CreateStudentRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string name */ 1:
                    message.name = reader.string();
                    break;
                case /* int32 age */ 2:
                    message.age = reader.int32();
                    break;
                case /* string class_name */ 3:
                    message.className = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CreateStudentRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string name = 1; */
        if (message.name !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.name);
        /* int32 age = 2; */
        if (message.age !== 0)
            writer.tag(2, WireType.Varint).int32(message.age);
        /* string class_name = 3; */
        if (message.className !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.className);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message student.CreateStudentRequest
 */
export const CreateStudentRequest = new CreateStudentRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CreateStudentReply$Type extends MessageType<CreateStudentReply> {
    constructor() {
        super("student.CreateStudentReply", [
            { no: 1, name: "student", kind: "message", T: () => StudentInfo }
        ]);
    }
    create(value?: PartialMessage<CreateStudentReply>): CreateStudentReply {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<CreateStudentReply>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CreateStudentReply): CreateStudentReply {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* student.StudentInfo student */ 1:
                    message.student = StudentInfo.internalBinaryRead(reader, reader.uint32(), options, message.student);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CreateStudentReply, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* student.StudentInfo student = 1; */
        if (message.student)
            StudentInfo.internalBinaryWrite(message.student, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message student.CreateStudentReply
 */
export const CreateStudentReply = new CreateStudentReply$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdateStudentRequest$Type extends MessageType<UpdateStudentRequest> {
    constructor() {
        super("student.UpdateStudentRequest", [
            { no: 1, name: "id", kind: "scalar", T: 3 /*ScalarType.INT64*/ },
            { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "age", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "class_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<UpdateStudentRequest>): UpdateStudentRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "0";
        message.name = "";
        message.age = 0;
        message.className = "";
        if (value !== undefined)
            reflectionMergePartial<UpdateStudentRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UpdateStudentRequest): UpdateStudentRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 id */ 1:
                    message.id = reader.int64().toString();
                    break;
                case /* string name */ 2:
                    message.name = reader.string();
                    break;
                case /* int32 age */ 3:
                    message.age = reader.int32();
                    break;
                case /* string class_name */ 4:
                    message.className = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UpdateStudentRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 id = 1; */
        if (message.id !== "0")
            writer.tag(1, WireType.Varint).int64(message.id);
        /* string name = 2; */
        if (message.name !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.name);
        /* int32 age = 3; */
        if (message.age !== 0)
            writer.tag(3, WireType.Varint).int32(message.age);
        /* string class_name = 4; */
        if (message.className !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.className);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message student.UpdateStudentRequest
 */
export const UpdateStudentRequest = new UpdateStudentRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdateStudentReply$Type extends MessageType<UpdateStudentReply> {
    constructor() {
        super("student.UpdateStudentReply", [
            { no: 1, name: "student", kind: "message", T: () => StudentInfo }
        ]);
    }
    create(value?: PartialMessage<UpdateStudentReply>): UpdateStudentReply {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<UpdateStudentReply>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UpdateStudentReply): UpdateStudentReply {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* student.StudentInfo student */ 1:
                    message.student = StudentInfo.internalBinaryRead(reader, reader.uint32(), options, message.student);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UpdateStudentReply, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* student.StudentInfo student = 1; */
        if (message.student)
            StudentInfo.internalBinaryWrite(message.student, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message student.UpdateStudentReply
 */
export const UpdateStudentReply = new UpdateStudentReply$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DeleteStudentRequest$Type extends MessageType<DeleteStudentRequest> {
    constructor() {
        super("student.DeleteStudentRequest", [
            { no: 1, name: "id", kind: "scalar", T: 3 /*ScalarType.INT64*/ }
        ]);
    }
    create(value?: PartialMessage<DeleteStudentRequest>): DeleteStudentRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "0";
        if (value !== undefined)
            reflectionMergePartial<DeleteStudentRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DeleteStudentRequest): DeleteStudentRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 id */ 1:
                    message.id = reader.int64().toString();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DeleteStudentRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 id = 1; */
        if (message.id !== "0")
            writer.tag(1, WireType.Varint).int64(message.id);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message student.DeleteStudentRequest
 */
export const DeleteStudentRequest = new DeleteStudentRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DeleteStudentReply$Type extends MessageType<DeleteStudentReply> {
    constructor() {
        super("student.DeleteStudentReply", [
            { no: 1, name: "success", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<DeleteStudentReply>): DeleteStudentReply {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.success = false;
        if (value !== undefined)
            reflectionMergePartial<DeleteStudentReply>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DeleteStudentReply): DeleteStudentReply {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool success */ 1:
                    message.success = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DeleteStudentReply, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool success = 1; */
        if (message.success !== false)
            writer.tag(1, WireType.Varint).bool(message.success);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message student.DeleteStudentReply
 */
export const DeleteStudentReply = new DeleteStudentReply$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetStudentRequest$Type extends MessageType<GetStudentRequest> {
    constructor() {
        super("student.GetStudentRequest", [
            { no: 1, name: "id", kind: "scalar", T: 3 /*ScalarType.INT64*/ }
        ]);
    }
    create(value?: PartialMessage<GetStudentRequest>): GetStudentRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "0";
        if (value !== undefined)
            reflectionMergePartial<GetStudentRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetStudentRequest): GetStudentRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 id */ 1:
                    message.id = reader.int64().toString();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetStudentRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 id = 1; */
        if (message.id !== "0")
            writer.tag(1, WireType.Varint).int64(message.id);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message student.GetStudentRequest
 */
export const GetStudentRequest = new GetStudentRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetStudentReply$Type extends MessageType<GetStudentReply> {
    constructor() {
        super("student.GetStudentReply", [
            { no: 1, name: "student", kind: "message", T: () => StudentInfo }
        ]);
    }
    create(value?: PartialMessage<GetStudentReply>): GetStudentReply {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<GetStudentReply>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetStudentReply): GetStudentReply {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* student.StudentInfo student */ 1:
                    message.student = StudentInfo.internalBinaryRead(reader, reader.uint32(), options, message.student);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetStudentReply, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* student.StudentInfo student = 1; */
        if (message.student)
            StudentInfo.internalBinaryWrite(message.student, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message student.GetStudentReply
 */
export const GetStudentReply = new GetStudentReply$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListStudentsRequest$Type extends MessageType<ListStudentsRequest> {
    constructor() {
        super("student.ListStudentsRequest", [
            { no: 1, name: "page", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "page_size", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<ListStudentsRequest>): ListStudentsRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.page = 0;
        message.pageSize = 0;
        if (value !== undefined)
            reflectionMergePartial<ListStudentsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListStudentsRequest): ListStudentsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 page */ 1:
                    message.page = reader.int32();
                    break;
                case /* int32 page_size */ 2:
                    message.pageSize = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListStudentsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 page = 1; */
        if (message.page !== 0)
            writer.tag(1, WireType.Varint).int32(message.page);
        /* int32 page_size = 2; */
        if (message.pageSize !== 0)
            writer.tag(2, WireType.Varint).int32(message.pageSize);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message student.ListStudentsRequest
 */
export const ListStudentsRequest = new ListStudentsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListStudentsReply$Type extends MessageType<ListStudentsReply> {
    constructor() {
        super("student.ListStudentsReply", [
            { no: 1, name: "students", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => StudentInfo },
            { no: 2, name: "count", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<ListStudentsReply>): ListStudentsReply {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.students = [];
        message.count = 0;
        if (value !== undefined)
            reflectionMergePartial<ListStudentsReply>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListStudentsReply): ListStudentsReply {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated student.StudentInfo students */ 1:
                    message.students.push(StudentInfo.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* int32 count */ 2:
                    message.count = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListStudentsReply, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated student.StudentInfo students = 1; */
        for (let i = 0; i < message.students.length; i++)
            StudentInfo.internalBinaryWrite(message.students[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* int32 count = 2; */
        if (message.count !== 0)
            writer.tag(2, WireType.Varint).int32(message.count);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message student.ListStudentsReply
 */
export const ListStudentsReply = new ListStudentsReply$Type();
/**
 * @generated ServiceType for protobuf service student.StudentService
 */
export const StudentService = new ServiceType("student.StudentService", [
    { name: "CreateStudent", options: { "google.api.http": { post: "/students", body: "*" } }, I: CreateStudentRequest, O: CreateStudentReply },
    { name: "UpdateStudent", options: { "google.api.http": { put: "/students/{id}", body: "*" } }, I: UpdateStudentRequest, O: UpdateStudentReply },
    { name: "DeleteStudent", options: { "google.api.http": { delete: "/students/{id}" } }, I: DeleteStudentRequest, O: DeleteStudentReply },
    { name: "GetStudent", options: { "google.api.http": { get: "/students/{id}" } }, I: GetStudentRequest, O: GetStudentReply },
    { name: "ListStudents", options: { "google.api.http": { get: "/students" } }, I: ListStudentsRequest, O: ListStudentsReply }
]);
