// @generated by protobuf-ts 2.11.1 with parameter long_type_string
// @generated from protobuf file "student/student.proto" (package "student", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { StudentService } from "./student";
import type { ListStudentsReply } from "./student";
import type { ListStudentsRequest } from "./student";
import type { GetStudentReply } from "./student";
import type { GetStudentRequest } from "./student";
import type { DeleteStudentReply } from "./student";
import type { DeleteStudentRequest } from "./student";
import type { UpdateStudentReply } from "./student";
import type { UpdateStudentRequest } from "./student";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { CreateStudentReply } from "./student";
import type { CreateStudentRequest } from "./student";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
import { executeGrpcToHttp } from '@yylego/grpc-to-http';
import type { GrpcToHttpPromise } from '@yylego/grpc-to-http';
/**
 * @generated from protobuf service student.StudentService
 */
export interface IStudentServiceClient {
    /**
     * @generated from protobuf rpc: CreateStudent
     */
    createStudent(input: CreateStudentRequest, options?: RpcOptions): GrpcToHttpPromise<CreateStudentRequest, CreateStudentReply>;
    /**
     * @generated from protobuf rpc: UpdateStudent
     */
    updateStudent(input: UpdateStudentRequest, options?: RpcOptions): GrpcToHttpPromise<UpdateStudentRequest, UpdateStudentReply>;
    /**
     * @generated from protobuf rpc: DeleteStudent
     */
    deleteStudent(input: DeleteStudentRequest, options?: RpcOptions): GrpcToHttpPromise<DeleteStudentRequest, DeleteStudentReply>;
    /**
     * @generated from protobuf rpc: GetStudent
     */
    getStudent(input: GetStudentRequest, options?: RpcOptions): GrpcToHttpPromise<GetStudentRequest, GetStudentReply>;
    /**
     * @generated from protobuf rpc: ListStudents
     */
    listStudents(input: ListStudentsRequest, options?: RpcOptions): GrpcToHttpPromise<ListStudentsRequest, ListStudentsReply>;
}
/**
 * @generated from protobuf service student.StudentService
 */
export class StudentServiceClient implements IStudentServiceClient, ServiceInfo {
    typeName = StudentService.typeName;
    methods = StudentService.methods;
    options = StudentService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: CreateStudent
     */
    createStudent(input: CreateStudentRequest, options?: RpcOptions): GrpcToHttpPromise<CreateStudentRequest, CreateStudentReply> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return executeGrpcToHttp<CreateStudentRequest, CreateStudentReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateStudent
     */
    updateStudent(input: UpdateStudentRequest, options?: RpcOptions): GrpcToHttpPromise<UpdateStudentRequest, UpdateStudentReply> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return executeGrpcToHttp<UpdateStudentRequest, UpdateStudentReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeleteStudent
     */
    deleteStudent(input: DeleteStudentRequest, options?: RpcOptions): GrpcToHttpPromise<DeleteStudentRequest, DeleteStudentReply> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return executeGrpcToHttp<DeleteStudentRequest, DeleteStudentReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetStudent
     */
    getStudent(input: GetStudentRequest, options?: RpcOptions): GrpcToHttpPromise<GetStudentRequest, GetStudentReply> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return executeGrpcToHttp<GetStudentRequest, GetStudentReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListStudents
     */
    listStudents(input: ListStudentsRequest, options?: RpcOptions): GrpcToHttpPromise<ListStudentsRequest, ListStudentsReply> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return executeGrpcToHttp<ListStudentsRequest, ListStudentsReply>("unary", this._transport, method, opt, input);
    }
}
