/* eslint-disable */
// @generated by protobuf-ts 2.11.1 with parameter ts_nocheck,eslint_disable,long_type_string
// @generated from protobuf file "article/article.proto" (package "article", syntax proto3)
// tslint:disable
// @ts-nocheck
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message article.ArticleInfo
 */
export interface ArticleInfo {
    /**
     * @generated from protobuf field: int64 id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: string title = 2
     */
    title: string;
    /**
     * @generated from protobuf field: string content = 3
     */
    content: string;
    /**
     * @generated from protobuf field: int64 student_id = 4
     */
    studentId: string;
}
/**
 * @generated from protobuf message article.CreateArticleRequest
 */
export interface CreateArticleRequest {
    /**
     * @generated from protobuf field: string title = 1
     */
    title: string;
    /**
     * @generated from protobuf field: string content = 2
     */
    content: string;
    /**
     * @generated from protobuf field: int64 student_id = 3
     */
    studentId: string;
}
/**
 * @generated from protobuf message article.CreateArticleReply
 */
export interface CreateArticleReply {
    /**
     * @generated from protobuf field: article.ArticleInfo article = 1
     */
    article?: ArticleInfo;
}
/**
 * @generated from protobuf message article.UpdateArticleRequest
 */
export interface UpdateArticleRequest {
    /**
     * @generated from protobuf field: int64 id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: string title = 2
     */
    title: string;
    /**
     * @generated from protobuf field: string content = 3
     */
    content: string;
    /**
     * @generated from protobuf field: int64 student_id = 4
     */
    studentId: string;
}
/**
 * @generated from protobuf message article.UpdateArticleReply
 */
export interface UpdateArticleReply {
    /**
     * @generated from protobuf field: article.ArticleInfo article = 1
     */
    article?: ArticleInfo;
}
/**
 * @generated from protobuf message article.DeleteArticleRequest
 */
export interface DeleteArticleRequest {
    /**
     * @generated from protobuf field: int64 id = 1
     */
    id: string;
}
/**
 * @generated from protobuf message article.DeleteArticleReply
 */
export interface DeleteArticleReply {
    /**
     * @generated from protobuf field: bool success = 1
     */
    success: boolean;
}
/**
 * @generated from protobuf message article.GetArticleRequest
 */
export interface GetArticleRequest {
    /**
     * @generated from protobuf field: int64 id = 1
     */
    id: string;
}
/**
 * @generated from protobuf message article.GetArticleReply
 */
export interface GetArticleReply {
    /**
     * @generated from protobuf field: article.ArticleInfo article = 1
     */
    article?: ArticleInfo;
}
/**
 * @generated from protobuf message article.ListArticlesRequest
 */
export interface ListArticlesRequest {
    /**
     * @generated from protobuf field: int32 page = 1
     */
    page: number;
    /**
     * @generated from protobuf field: int32 page_size = 2
     */
    pageSize: number;
}
/**
 * @generated from protobuf message article.ListStudentArticlesRequest
 */
export interface ListStudentArticlesRequest {
    /**
     * @generated from protobuf field: int64 student_id = 1
     */
    studentId: string;
    /**
     * @generated from protobuf field: int32 page = 2
     */
    page: number;
    /**
     * @generated from protobuf field: int32 page_size = 3
     */
    pageSize: number;
}
/**
 * @generated from protobuf message article.ListArticlesReply
 */
export interface ListArticlesReply {
    /**
     * @generated from protobuf field: repeated article.ArticleInfo articles = 1
     */
    articles: ArticleInfo[];
    /**
     * @generated from protobuf field: int32 count = 2
     */
    count: number;
}
// @generated message type with reflection information, may provide speed optimized methods
class ArticleInfo$Type extends MessageType<ArticleInfo> {
    constructor() {
        super("article.ArticleInfo", [
            { no: 1, name: "id", kind: "scalar", T: 3 /*ScalarType.INT64*/ },
            { no: 2, name: "title", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "content", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "student_id", kind: "scalar", T: 3 /*ScalarType.INT64*/ }
        ]);
    }
    create(value?: PartialMessage<ArticleInfo>): ArticleInfo {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "0";
        message.title = "";
        message.content = "";
        message.studentId = "0";
        if (value !== undefined)
            reflectionMergePartial<ArticleInfo>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ArticleInfo): ArticleInfo {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 id */ 1:
                    message.id = reader.int64().toString();
                    break;
                case /* string title */ 2:
                    message.title = reader.string();
                    break;
                case /* string content */ 3:
                    message.content = reader.string();
                    break;
                case /* int64 student_id */ 4:
                    message.studentId = reader.int64().toString();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ArticleInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 id = 1; */
        if (message.id !== "0")
            writer.tag(1, WireType.Varint).int64(message.id);
        /* string title = 2; */
        if (message.title !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.title);
        /* string content = 3; */
        if (message.content !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.content);
        /* int64 student_id = 4; */
        if (message.studentId !== "0")
            writer.tag(4, WireType.Varint).int64(message.studentId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message article.ArticleInfo
 */
export const ArticleInfo = new ArticleInfo$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CreateArticleRequest$Type extends MessageType<CreateArticleRequest> {
    constructor() {
        super("article.CreateArticleRequest", [
            { no: 1, name: "title", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "content", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "student_id", kind: "scalar", T: 3 /*ScalarType.INT64*/ }
        ]);
    }
    create(value?: PartialMessage<CreateArticleRequest>): CreateArticleRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.title = "";
        message.content = "";
        message.studentId = "0";
        if (value !== undefined)
            reflectionMergePartial<CreateArticleRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CreateArticleRequest): CreateArticleRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string title */ 1:
                    message.title = reader.string();
                    break;
                case /* string content */ 2:
                    message.content = reader.string();
                    break;
                case /* int64 student_id */ 3:
                    message.studentId = reader.int64().toString();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CreateArticleRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string title = 1; */
        if (message.title !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.title);
        /* string content = 2; */
        if (message.content !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.content);
        /* int64 student_id = 3; */
        if (message.studentId !== "0")
            writer.tag(3, WireType.Varint).int64(message.studentId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message article.CreateArticleRequest
 */
export const CreateArticleRequest = new CreateArticleRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CreateArticleReply$Type extends MessageType<CreateArticleReply> {
    constructor() {
        super("article.CreateArticleReply", [
            { no: 1, name: "article", kind: "message", T: () => ArticleInfo }
        ]);
    }
    create(value?: PartialMessage<CreateArticleReply>): CreateArticleReply {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<CreateArticleReply>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CreateArticleReply): CreateArticleReply {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* article.ArticleInfo article */ 1:
                    message.article = ArticleInfo.internalBinaryRead(reader, reader.uint32(), options, message.article);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CreateArticleReply, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* article.ArticleInfo article = 1; */
        if (message.article)
            ArticleInfo.internalBinaryWrite(message.article, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message article.CreateArticleReply
 */
export const CreateArticleReply = new CreateArticleReply$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdateArticleRequest$Type extends MessageType<UpdateArticleRequest> {
    constructor() {
        super("article.UpdateArticleRequest", [
            { no: 1, name: "id", kind: "scalar", T: 3 /*ScalarType.INT64*/ },
            { no: 2, name: "title", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "content", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "student_id", kind: "scalar", T: 3 /*ScalarType.INT64*/ }
        ]);
    }
    create(value?: PartialMessage<UpdateArticleRequest>): UpdateArticleRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "0";
        message.title = "";
        message.content = "";
        message.studentId = "0";
        if (value !== undefined)
            reflectionMergePartial<UpdateArticleRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UpdateArticleRequest): UpdateArticleRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 id */ 1:
                    message.id = reader.int64().toString();
                    break;
                case /* string title */ 2:
                    message.title = reader.string();
                    break;
                case /* string content */ 3:
                    message.content = reader.string();
                    break;
                case /* int64 student_id */ 4:
                    message.studentId = reader.int64().toString();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UpdateArticleRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 id = 1; */
        if (message.id !== "0")
            writer.tag(1, WireType.Varint).int64(message.id);
        /* string title = 2; */
        if (message.title !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.title);
        /* string content = 3; */
        if (message.content !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.content);
        /* int64 student_id = 4; */
        if (message.studentId !== "0")
            writer.tag(4, WireType.Varint).int64(message.studentId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message article.UpdateArticleRequest
 */
export const UpdateArticleRequest = new UpdateArticleRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdateArticleReply$Type extends MessageType<UpdateArticleReply> {
    constructor() {
        super("article.UpdateArticleReply", [
            { no: 1, name: "article", kind: "message", T: () => ArticleInfo }
        ]);
    }
    create(value?: PartialMessage<UpdateArticleReply>): UpdateArticleReply {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<UpdateArticleReply>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UpdateArticleReply): UpdateArticleReply {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* article.ArticleInfo article */ 1:
                    message.article = ArticleInfo.internalBinaryRead(reader, reader.uint32(), options, message.article);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UpdateArticleReply, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* article.ArticleInfo article = 1; */
        if (message.article)
            ArticleInfo.internalBinaryWrite(message.article, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message article.UpdateArticleReply
 */
export const UpdateArticleReply = new UpdateArticleReply$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DeleteArticleRequest$Type extends MessageType<DeleteArticleRequest> {
    constructor() {
        super("article.DeleteArticleRequest", [
            { no: 1, name: "id", kind: "scalar", T: 3 /*ScalarType.INT64*/ }
        ]);
    }
    create(value?: PartialMessage<DeleteArticleRequest>): DeleteArticleRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "0";
        if (value !== undefined)
            reflectionMergePartial<DeleteArticleRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DeleteArticleRequest): DeleteArticleRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 id */ 1:
                    message.id = reader.int64().toString();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DeleteArticleRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 id = 1; */
        if (message.id !== "0")
            writer.tag(1, WireType.Varint).int64(message.id);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message article.DeleteArticleRequest
 */
export const DeleteArticleRequest = new DeleteArticleRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DeleteArticleReply$Type extends MessageType<DeleteArticleReply> {
    constructor() {
        super("article.DeleteArticleReply", [
            { no: 1, name: "success", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<DeleteArticleReply>): DeleteArticleReply {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.success = false;
        if (value !== undefined)
            reflectionMergePartial<DeleteArticleReply>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DeleteArticleReply): DeleteArticleReply {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool success */ 1:
                    message.success = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DeleteArticleReply, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool success = 1; */
        if (message.success !== false)
            writer.tag(1, WireType.Varint).bool(message.success);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message article.DeleteArticleReply
 */
export const DeleteArticleReply = new DeleteArticleReply$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetArticleRequest$Type extends MessageType<GetArticleRequest> {
    constructor() {
        super("article.GetArticleRequest", [
            { no: 1, name: "id", kind: "scalar", T: 3 /*ScalarType.INT64*/ }
        ]);
    }
    create(value?: PartialMessage<GetArticleRequest>): GetArticleRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "0";
        if (value !== undefined)
            reflectionMergePartial<GetArticleRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetArticleRequest): GetArticleRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 id */ 1:
                    message.id = reader.int64().toString();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetArticleRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 id = 1; */
        if (message.id !== "0")
            writer.tag(1, WireType.Varint).int64(message.id);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message article.GetArticleRequest
 */
export const GetArticleRequest = new GetArticleRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetArticleReply$Type extends MessageType<GetArticleReply> {
    constructor() {
        super("article.GetArticleReply", [
            { no: 1, name: "article", kind: "message", T: () => ArticleInfo }
        ]);
    }
    create(value?: PartialMessage<GetArticleReply>): GetArticleReply {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<GetArticleReply>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetArticleReply): GetArticleReply {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* article.ArticleInfo article */ 1:
                    message.article = ArticleInfo.internalBinaryRead(reader, reader.uint32(), options, message.article);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetArticleReply, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* article.ArticleInfo article = 1; */
        if (message.article)
            ArticleInfo.internalBinaryWrite(message.article, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message article.GetArticleReply
 */
export const GetArticleReply = new GetArticleReply$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListArticlesRequest$Type extends MessageType<ListArticlesRequest> {
    constructor() {
        super("article.ListArticlesRequest", [
            { no: 1, name: "page", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "page_size", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<ListArticlesRequest>): ListArticlesRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.page = 0;
        message.pageSize = 0;
        if (value !== undefined)
            reflectionMergePartial<ListArticlesRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListArticlesRequest): ListArticlesRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 page */ 1:
                    message.page = reader.int32();
                    break;
                case /* int32 page_size */ 2:
                    message.pageSize = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListArticlesRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 page = 1; */
        if (message.page !== 0)
            writer.tag(1, WireType.Varint).int32(message.page);
        /* int32 page_size = 2; */
        if (message.pageSize !== 0)
            writer.tag(2, WireType.Varint).int32(message.pageSize);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message article.ListArticlesRequest
 */
export const ListArticlesRequest = new ListArticlesRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListStudentArticlesRequest$Type extends MessageType<ListStudentArticlesRequest> {
    constructor() {
        super("article.ListStudentArticlesRequest", [
            { no: 1, name: "student_id", kind: "scalar", T: 3 /*ScalarType.INT64*/ },
            { no: 2, name: "page", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "page_size", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<ListStudentArticlesRequest>): ListStudentArticlesRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.studentId = "0";
        message.page = 0;
        message.pageSize = 0;
        if (value !== undefined)
            reflectionMergePartial<ListStudentArticlesRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListStudentArticlesRequest): ListStudentArticlesRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 student_id */ 1:
                    message.studentId = reader.int64().toString();
                    break;
                case /* int32 page */ 2:
                    message.page = reader.int32();
                    break;
                case /* int32 page_size */ 3:
                    message.pageSize = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListStudentArticlesRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 student_id = 1; */
        if (message.studentId !== "0")
            writer.tag(1, WireType.Varint).int64(message.studentId);
        /* int32 page = 2; */
        if (message.page !== 0)
            writer.tag(2, WireType.Varint).int32(message.page);
        /* int32 page_size = 3; */
        if (message.pageSize !== 0)
            writer.tag(3, WireType.Varint).int32(message.pageSize);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message article.ListStudentArticlesRequest
 */
export const ListStudentArticlesRequest = new ListStudentArticlesRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListArticlesReply$Type extends MessageType<ListArticlesReply> {
    constructor() {
        super("article.ListArticlesReply", [
            { no: 1, name: "articles", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => ArticleInfo },
            { no: 2, name: "count", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<ListArticlesReply>): ListArticlesReply {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.articles = [];
        message.count = 0;
        if (value !== undefined)
            reflectionMergePartial<ListArticlesReply>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListArticlesReply): ListArticlesReply {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated article.ArticleInfo articles */ 1:
                    message.articles.push(ArticleInfo.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* int32 count */ 2:
                    message.count = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListArticlesReply, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated article.ArticleInfo articles = 1; */
        for (let i = 0; i < message.articles.length; i++)
            ArticleInfo.internalBinaryWrite(message.articles[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* int32 count = 2; */
        if (message.count !== 0)
            writer.tag(2, WireType.Varint).int32(message.count);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message article.ListArticlesReply
 */
export const ListArticlesReply = new ListArticlesReply$Type();
/**
 * @generated ServiceType for protobuf service article.ArticleService
 */
export const ArticleService = new ServiceType("article.ArticleService", [
    { name: "CreateArticle", options: { "google.api.http": { post: "/articles", body: "*" } }, I: CreateArticleRequest, O: CreateArticleReply },
    { name: "UpdateArticle", options: { "google.api.http": { put: "/articles/{id}", body: "*" } }, I: UpdateArticleRequest, O: UpdateArticleReply },
    { name: "DeleteArticle", options: { "google.api.http": { delete: "/articles/{id}" } }, I: DeleteArticleRequest, O: DeleteArticleReply },
    { name: "GetArticle", options: { "google.api.http": { get: "/articles/{id}" } }, I: GetArticleRequest, O: GetArticleReply },
    { name: "ListArticles", options: { "google.api.http": { get: "/articles" } }, I: ListArticlesRequest, O: ListArticlesReply },
    { name: "ListStudentArticles", options: { "google.api.http": { get: "/students/{student_id}/articles" } }, I: ListStudentArticlesRequest, O: ListArticlesReply }
]);
