// @generated by protobuf-ts 2.11.1 with parameter long_type_string
// @generated from protobuf file "article/article.proto" (package "article", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { ArticleService } from "./article";
import type { ListArticlesReply } from "./article";
import type { ListArticlesRequest } from "./article";
import type { GetArticleReply } from "./article";
import type { GetArticleRequest } from "./article";
import type { DeleteArticleReply } from "./article";
import type { DeleteArticleRequest } from "./article";
import type { UpdateArticleReply } from "./article";
import type { UpdateArticleRequest } from "./article";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { CreateArticleReply } from "./article";
import type { CreateArticleRequest } from "./article";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
import { executeGrpcToHttp } from '@yylego/grpc-to-http';
import type { GrpcToHttpPromise } from '@yylego/grpc-to-http';
/**
 * @generated from protobuf service article.ArticleService
 */
export interface IArticleServiceClient {
    /**
     * @generated from protobuf rpc: CreateArticle
     */
    createArticle(input: CreateArticleRequest, options?: RpcOptions): GrpcToHttpPromise<CreateArticleRequest, CreateArticleReply>;
    /**
     * @generated from protobuf rpc: UpdateArticle
     */
    updateArticle(input: UpdateArticleRequest, options?: RpcOptions): GrpcToHttpPromise<UpdateArticleRequest, UpdateArticleReply>;
    /**
     * @generated from protobuf rpc: DeleteArticle
     */
    deleteArticle(input: DeleteArticleRequest, options?: RpcOptions): GrpcToHttpPromise<DeleteArticleRequest, DeleteArticleReply>;
    /**
     * @generated from protobuf rpc: GetArticle
     */
    getArticle(input: GetArticleRequest, options?: RpcOptions): GrpcToHttpPromise<GetArticleRequest, GetArticleReply>;
    /**
     * @generated from protobuf rpc: ListArticles
     */
    listArticles(input: ListArticlesRequest, options?: RpcOptions): GrpcToHttpPromise<ListArticlesRequest, ListArticlesReply>;
}
/**
 * @generated from protobuf service article.ArticleService
 */
export class ArticleServiceClient implements IArticleServiceClient, ServiceInfo {
    typeName = ArticleService.typeName;
    methods = ArticleService.methods;
    options = ArticleService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: CreateArticle
     */
    createArticle(input: CreateArticleRequest, options?: RpcOptions): GrpcToHttpPromise<CreateArticleRequest, CreateArticleReply> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return executeGrpcToHttp<CreateArticleRequest, CreateArticleReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateArticle
     */
    updateArticle(input: UpdateArticleRequest, options?: RpcOptions): GrpcToHttpPromise<UpdateArticleRequest, UpdateArticleReply> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return executeGrpcToHttp<UpdateArticleRequest, UpdateArticleReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeleteArticle
     */
    deleteArticle(input: DeleteArticleRequest, options?: RpcOptions): GrpcToHttpPromise<DeleteArticleRequest, DeleteArticleReply> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return executeGrpcToHttp<DeleteArticleRequest, DeleteArticleReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetArticle
     */
    getArticle(input: GetArticleRequest, options?: RpcOptions): GrpcToHttpPromise<GetArticleRequest, GetArticleReply> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return executeGrpcToHttp<GetArticleRequest, GetArticleReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListArticles
     */
    listArticles(input: ListArticlesRequest, options?: RpcOptions): GrpcToHttpPromise<ListArticlesRequest, ListArticlesReply> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return executeGrpcToHttp<ListArticlesRequest, ListArticlesReply>("unary", this._transport, method, opt, input);
    }
}
