/* eslint-disable */
// @generated by protobuf-ts 2.11.1 with parameter ts_nocheck,eslint_disable,long_type_string
// @generated from protobuf file "article/reason_enum.proto" (package "article", syntax proto3)
// tslint:disable
// @ts-nocheck
/**
 * @generated from protobuf enum article.ErrorReason
 */
export enum ErrorReason {
    /**
     * @generated from protobuf enum value: UNKNOWN = 0;
     */
    UNKNOWN = 0,
    /**
     * @generated from protobuf enum value: BAD_PARAM = 40000;
     */
    BAD_PARAM = 40000,
    /**
     * @generated from protobuf enum value: ARTICLE_NOT_FOUND = 40400;
     */
    ARTICLE_NOT_FOUND = 40400,
    /**
     * @generated from protobuf enum value: SERVER_ERROR = 50000;
     */
    SERVER_ERROR = 50000,
    /**
     * @generated from protobuf enum value: DB_ERROR = 50001;
     */
    DB_ERROR = 50001,
    /**
     * @generated from protobuf enum value: TX_ERROR = 50002;
     */
    TX_ERROR = 50002,
    /**
     * @generated from protobuf enum value: ARTICLE_CREATE_FAILURE = 50003;
     */
    ARTICLE_CREATE_FAILURE = 50003
}
